server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiajiaoxiaochengxu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Oyyb258369!
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

coisini:
  security:
    jwt-key: coisini
    # 过期时间
    token-expired-in: 86400000

logging:
  level:
    com: debug
nas:
  basepath: "/home/nas"
  ffmpeg-bin-dir: "/home/nas/ffmpeg"
  # 转码目录位置
  out-dir: "/home/nas/ts"
  base-url: http://114.215.194.16:8081/nas/file
